# g++
# Build your C++ projects with g++ and GNU Make.
# https://aka.ms/yaml

pool:
  name: Azure Pipelines
  vmImage: docker_x86_test

# specific branch build with batching
trigger:
  batch: true
  branches:
    include:
        - master
  paths:
      exclude:
          - "docs/*"
          - "*.md"

pr:
    autoCancel: true
    branches:
        include:
            - master

#variables:
#  system.debug: 'true'

steps:
    - script: |
        env
