# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    env | sort
    echo $0
    cat $0
    echo $XXXXX
    /home/stellarci/myagent/source_docker_machine
    export TEST=$(/home/stellarci/myagent/source_docker_machine)
    echo $TEST
  displayName: 'Run a multi-line script'
